name: Deploy Nebula to Azure

on:
  push:
    branches:
      - main  # cada vez que hagas push a main, se actualiza en Azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NebulaML'  # nombre exacto de tu App Service
          slot-name: 'production'
          publish-profile: ${{ secrets.SECRET_NEBULAML }}
          images: |
            nebulacanadaacr.azurecr.io/nebula-image-frontend:latest
            nebulacanadaacr.azurecr.io/nebula-image-backend:latest